name: 打包
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 拉取仓库
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: 安装MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: 构建RL real
      if: success()
      run: |
        msbuild RainLanguage\RainLanguage\RainLanguage.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
        msbuild RainLanguage\RainDebuggerDetector\RainDebuggerDetector.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
        msbuild RainLanguage\RainLauncher\RainLauncher.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64
  
    - name: 构建RL fixed
      if: success()
      run: |
        msbuild RainLanguage\RainLanguage\RainLanguage.vcxproj -t:rebuild -verbosity:m -property:Configuration=ReleaseFixed -property:Platform=x64
        msbuild RainLanguage\RainDebuggerDetector\RainDebuggerDetector.vcxproj -t:rebuild -verbosity:m -property:Configuration=ReleaseFixed -property:Platform=x64
        msbuild RainLanguage\RainLauncher\RainLauncher.vcxproj -t:rebuild -verbosity:m -property:Configuration=ReleaseFixed -property:Platform=x64
    
    - name: 构建Injector
      if: success()
      run: msbuild RainLanguage\RainDebuggerInjector\RainDebuggerInjector.vcxproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=x64

    - name: 安装NuGet
      if: success()
      uses: nuget/setup-nuget@v2
      
    - name: 构建Server
      if: success()
      run: |
        nuget restore RainLanguage\RainLanguage.sln
        msbuild RainLanguageServer\RainLanguageServer\RainLanguageServer.csproj -t:rebuild -verbosity:m -property:Configuration=Release -property:Platform=AnyCPU
        
    - name: 安装Node.js
      if: success()
      uses: actions/setup-node@v4
      with:
        node-version: '>=17.0.21'
    - name: 构建VSC扩展包
      if: success()
      run: |
        npm run dependencies
        npm run build
        npm run package
    - name: 上传vscode扩展包
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: RL-VSCodeExtension
        path: rain-language-1.0.0.vsix
        retention-days: 1
        if-no-files-found: error
    
